<?xml version="1.0" encoding="utf-8"?><Database Name="RESITER_MDS_v2" Class="BackboneDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\MSSQLSERVER_2012;Initial Catalog=RESITER_MDS_v2;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RESITER_MDS_v2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="" Member="Authenticates">
    <Type Name="Authenticate">
      <Column Name="username" Type="System.String" CanBeNull="false" />
      <Column Name="password" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.V_Usuarios" Member="Users">
    <Type Name="User">
      <Column Name="ENTI_Nombre" Member="name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ENTI_Email" Member="email" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ENTI_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ENTI_FechaCreacion" Member="createdAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ARCH_Token" Member="photo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="USUA_LANG_Nombre" Member="language" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="USUA_UltimaConexion" Member="lastLogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MAE_Archivo" Member="Files">
    <Type Name="File">
      <Column Name="ARCH_Nombre" Member="name" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="ARCH_Tamano" Member="length" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ARCH_FechaCreacion" Member="createdAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ARCH_ContentType" Member="contentType" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ARCH_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MAE_ArchivoBinario" Member="FileDatas">
    <Type Name="FileData">
      <Column Name="ARCH_Binario" Member="binary" Type="System.Byte[]" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ARCH_Nombre" Member="name" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="ARCH_ContentType" Member="contentType" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MAE_Perfil" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="ENTI_Nombre" Member="name" Storage="_ENTI_Nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ENTI_Token" Member="token" Storage="_ENTI_Token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Seleccionado" Member="selected" Type="System.Boolean" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.V_Perfiles" Member="Profiles">
    <Type Name="Profile">
      <Column Name="ENTI_Email" Member="email" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ENTI_Nombre" Member="name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ENTI_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ENTI_FechaCreacion" Member="createdAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PERF_Descripcion" Member="description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="PERF_Identificador" Member="identifier" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </Type>
  </Table>
</Database>