<?xml version="1.0" encoding="utf-8"?><Database Name="RS_MDS_v2" Class="AdministrationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\MSSQLSERVER_2012;Initial Catalog=RS_MDS_v2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RS_MDS_v2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="" Member="Menus">
    <Type Name="Menu">
      <Column Name="MITE_Nombre" Member="nombre" Storage="_MENUPERF_Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MITE_Url" Member="url" Storage="_MENUPERF_Url" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MITE_Icono" Member="icono" Storage="_MENUPERF_Icono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MITE_IconoCategoria" Member="categoriaIcono" Storage="_MENUPERF_IconoCategoria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MCAT_Nombre" Member="categoria" Storage="_MCAT_Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MCAT_Token" Member="token" Storage="_MCAT_Token" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="Estadisticas">
    <Type Name="Estadistica">
      <Column Name="Total" Member="total" Type="System.Int32" CanBeNull="false" />
      <Column Name="Realizados" Member="realizados" Type="System.Int32" CanBeNull="false" />
      <Column Name="Fallidos" Member="fallidos" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Estadistica_Conductors">
    <Type Name="Estadistica_Conductor">
      <Column Name="COND_SGS" Member="sgs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COND_Run" Member="run" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COND_Dv" Member="dv" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="ENTI_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ENTI_Nombre" Member="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Total" Member="total" Type="System.Int32" CanBeNull="false" />
      <Column Name="completados" Type="System.Int32" DbType="Completados" CanBeNull="false" />
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TotalProgramados" Type="System.Int32" CanBeNull="false" />
      <Column Name="TotalAdicionales" Type="System.Int32" CanBeNull="false" />
      <Column Name="AdicionalesFallidos" Type="System.Int32" CanBeNull="false" />
      <Column Name="ProgramadosRealizados" Type="System.Int32" CanBeNull="false" />
      <Column Name="ProgramadosFallidos" Type="System.Int32" CanBeNull="false" />
      <Column Name="AdicionalesRealizados" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MAE_ArchivoBinario" Member="Binarios">
    <Type Name="Binario">
      <Column Name="ARCH_Nombre" Member="nombre" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="ARCH_ContentType" Member="tipoContenido" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ARCH_Binario" Member="binario" Storage="_binary" Type="System.Byte[]" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.V_TipoServicio" Member="TipoServicios">
    <Type Name="TipoServicio">
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TISE_Nombre" Member="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TISE_Descripcion" Member="descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TISE_Fecha" Member="creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TISE_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier" IsPrimaryKey="true" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_UnidadDeNegocio" Member="UnidadDeNegocios">
    <Type Name="UnidadDeNegocio">
      <Column Name="DOCU_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SUCU_Nombre" Member="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CLIE_Nombre" Member="cliente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DOCU_Fecha" Member="creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SUCU_Latitud" Member="latitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SUCU_Longitud" Member="longitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SUCU_Zoom" Member="zoom" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_Clientes" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CLIE_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="CLIE_Nombre" Member="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CLIE_SGS" Member="sgs" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CLIE_Fecha" Member="creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_SucursalesCliente" Member="Sucursals">
    <Type Name="Sucursal">
      <Column Name="CLIE_Token" Member="cliente" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SUCU_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="SUCU_Nombre" Member="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SUCU_SGS" Member="sgs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUCU_Fecha" Member="creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Configurada" Member="configurada" Type="System.Boolean" DbType="Bool NOT NULL" CanBeNull="false" />
      <Column Name="SUCU_Latitud" Member="latitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SUCU_Longitud" Member="longitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SUCU_Zoom" Member="zoom" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_Vehiculos" Member="Vehiculos">
    <Type Name="Vehiculo">
      <Column Name="TIVE_Nombre" Member="tipo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VEHI_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="VEHI_Patente" Member="patente" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VEHI_SGS" Member="sgs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VEHI_Fecha" Member="creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Identificador" Member="identificador" Type="System.String" DbType="VarChar(223)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_Conductores" Member="Conductors">
    <Type Name="Conductor">
      <Column Name="ENTI_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ENTI_Nombre" Member="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ENTI_Email" Member="email" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ENTI_FechaCreacion" Member="creacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="COND_Run" Member="run" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COND_Dv" Member="dv" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="COND_SGS" Member="sgs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Identificador" Member="identificador" Type="System.String" DbType="VarChar(223)" CanBeNull="true" />
      <Column Name="hojaRuta" Member="puntos" Storage="_hojaRuta" Type="List&lt;PuntoRuta&gt;" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_Contratos" Member="Contratos">
    <Type Name="Contrato">
      <Column Name="CNTR_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CNTR_SGS" Member="sgs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CNTR_Fecha" Member="creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Identificador" Member="identificador" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MDS_Comportamiento" Member="Servicios">
    <Type Name="Servicio">
      <Column Name="COMP_HojaRuta" Member="hojaRuta" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="COMP_FotoOk" Member="fotoOk" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="COMP_FotoNOK" Member="fotoNOK" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="COMP_LecturaQR" Member="lecturaQR" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="COMP_Disposicion" Member="disposicion" Type="System.Boolean" CanBeNull="false" />
      <Column Name="TISE_Nombre" Member="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CNTR_Token" Member="contrato" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CNTR_Identificador" Member="identificador" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TISE_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_TipoPoligono" Member="TipoPoligonos">
    <Type Name="TipoPoligono">
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TIPO_Nombre" Member="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TIPO_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TIPO_Fecha" Member="creacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TIPO_Descripcion" Member="descripcion" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TIPO_Identificador" Member="identificador" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MDS_Poligono" Member="Poligonos">
    <Type Name="Poligono">
      <Column Name="POLI_Nombre" Member="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POLI_Fecha" Member="creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="POLI_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TIPO_Identificador" Member="tipo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="coordenadas" Type="List&lt;Models.Coordenada&gt;" CanBeNull="false" />
      <Column Name="servicios" Type="List&lt;String&gt;" CanBeNull="false" />
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="Coordenadas">
    <Type Name="Coordenada">
      <Column Name="lat" Type="System.Double" CanBeNull="false" />
      <Column Name="lng" Type="System.Double" CanBeNull="false" />
      <Column Name="zoom" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MDS_CoordenadasPoligono" Member="TB_MDS_CoordenadasPoligonos">
    <Type Name="TB_MDS_CoordenadasPoligono">
      <Column Name="CORD_Latitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CORD_Longitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CORD_Ordinal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="POLI_Token" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MDS_TipoServicio" Member="TB_MDS_TipoServicios">
    <Type Name="TB_MDS_TipoServicio">
      <Column Name="TISE_Token" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="POLI_Token" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="PuntoRutas">
    <Type Name="PuntoRuta">
      <Column Name="DOCU_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="VEHI_Token" Member="vehiculo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="POLI_Token" Member="poligono" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ENTI_Token" Member="conductor" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TISE_Token" Member="tipo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ESTA_Identificador" Member="estado" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_GPS_ServicioConductor" Member="ServicioConductors">
    <Type Name="ServicioConductor">
      <Column Name="" Member="foto" Storage="_imagen" Type="System.String" CanBeNull="true" />
      <Column Name="SERC_CodigoActivo" Member="qr" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="motivo" Type="System.String" CanBeNull="false" />
      <Column Name="Estado" Member="estado" Type="System.String" CanBeNull="false" />
      <Column Name="nivel" Type="System.String" CanBeNull="false" />
      <Column Name="TISE_Token" Member="tipo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_GPS_CoordenadaConductor" Member="CoordenadaConductors">
    <Type Name="CoordenadaConductor">
      <Column Name="CORA_Latitud" Member="latitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CORA_Longitud" Member="longitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ENTI_Token" Member="conductor" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VEHI_Token" Member="vehiculo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CORA_Fecha" Member="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_GPS_ServicioConductor" Member="TB_GPS_ServicioConductors">
    <Type Name="TB_GPS_ServicioConductor">
      <Column Name="SERC_CORD_Latitud" Member="latitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SERC_CORD_Longitud" Member="longitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SERC_Fecha" Member="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DOCU_Token" Member="ruta" Type="System.Guid" DbType="UNIQUEIDENTIFIER" CanBeNull="true" />
      <Column Name="SERC_CodigoActivo" Member="codigoActivo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SERC_NumeroVisible" Member="numeroVisible" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SERC_Volumen" Member="volumen" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ENTI_Token" Member="conductor" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VEHI_Token" Member="vehiculo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TISE_Token" Member="tipo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SERC_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SERC_Motivo" Member="motivo" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ESTA_Identificador" Member="estado" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="POLI_Token" Member="poligono" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ESTA_Nombre" Member="nombre" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="ResumenEstadisticas">
    <Type Name="ResumenEstadistica">
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="COND_Run" Member="run" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COND_Dv" Member="dv" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="ENTI_Nombre" Member="conductor" Storage="_nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="VEHI_Patente" Member="patente" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Adicionales" Member="adicionales" Type="System.Int32" CanBeNull="false" />
      <Column Name="Programados" Member="programados" Type="System.Int32" CanBeNull="false" />
      <Column Name="Realizados" Member="realizados" Type="System.Int32" CanBeNull="false" />
      <Column Name="Fallidos" Member="fallidos" Type="System.Int32" CanBeNull="false" />
      <Column Name="Total" Member="total" Type="System.Int32" CanBeNull="false" />
      <Column Name="TISE_Nombre" Member="tipo" Type="System.String" CanBeNull="false" />
      <Column Name="POLI_Nombre" Member="poligono" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="ResumenUnidadNegocios">
    <Type Name="ResumenUnidadNegocio">
      <Column Name="Vehiculos" Member="vehiculos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Poligonos" Member="poligonos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Conductores" Member="conductores" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Servicios" Member="servicios" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Usuarios" Member="usuarios" Type="System.String" CanBeNull="false" />
      <Column Name="SUCU_Nombre" Member="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CLIE_Nombre" Member="cliente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SUCU_Latitud" Member="latitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SUCU_Longitud" Member="longitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SUCU_Zoom" Member="zoom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOCU_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Motivos">
    <Type Name="Motivo">
      <Column Name="MOTISE_TISE_Codigo" Member="CodigoTipoServicio" Type="System.Int32" CanBeNull="false" />
      <Column Name="MO_Descripcion" Member="DescripcionMotivo" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>