#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Areas.Resiter.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RS_MDS_v2")]
	public partial class DriverDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInformacionServicio(InformacionServicio instance);
    partial void UpdateInformacionServicio(InformacionServicio instance);
    partial void DeleteInformacionServicio(InformacionServicio instance);
    #endregion
		
		public DriverDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RS_MDS_v2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DriverDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DriverDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DriverDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DriverDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InformacionServicio> InformacionServicios
		{
			get
			{
				return this.GetTable<InformacionServicio>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_GPS_ServicioConductor")]
	public partial class InformacionServicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _SERC_CORD_Latitud;
		
		private double _SERC_CORD_Longitud;
		
		private System.DateTime _SERC_Fecha;
		
		private System.Nullable<int> _SERC_ARCH_Codigo;
		
		private string _SERC_Motivo;
		
		private string _SERC_CodigoActivo;
		
		private string _SERC_NumeroVisible;
		
		private string _SERC_Volumen;
		
		private System.Nullable<System.Guid> _SERC_Token;
		
		private string _ENTI_Nombre;
		
		private string _CLIE_Nombre;
		
		private string _SUCU_Nombre;
		
		private string _VEHI_Patente;
		
		private string _TISE_Nombre;
		
		private int _COND_Run;
		
		private char _COND_Dv;
		
		private string _ESTA_Nombre;
		
		private string _POLI_Nombre;
		
		private int _SERC_Codigo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSERC_CORD_LatitudChanging(double value);
    partial void OnSERC_CORD_LatitudChanged();
    partial void OnSERC_CORD_LongitudChanging(double value);
    partial void OnSERC_CORD_LongitudChanged();
    partial void OnSERC_FechaChanging(System.DateTime value);
    partial void OnSERC_FechaChanged();
    partial void OnSERC_ARCH_CodigoChanging(System.Nullable<int> value);
    partial void OnSERC_ARCH_CodigoChanged();
    partial void OnSERC_MotivoChanging(string value);
    partial void OnSERC_MotivoChanged();
    partial void OnSERC_CodigoActivoChanging(string value);
    partial void OnSERC_CodigoActivoChanged();
    partial void OnSERC_NumeroVisibleChanging(string value);
    partial void OnSERC_NumeroVisibleChanged();
    partial void OnSERC_VolumenChanging(string value);
    partial void OnSERC_VolumenChanged();
    partial void OnSERC_TokenChanging(System.Nullable<System.Guid> value);
    partial void OnSERC_TokenChanged();
    partial void OnENTI_NombreChanging(string value);
    partial void OnENTI_NombreChanged();
    partial void OnCLIE_NombreChanging(string value);
    partial void OnCLIE_NombreChanged();
    partial void OnSUCU_NombreChanging(string value);
    partial void OnSUCU_NombreChanged();
    partial void OnVEHI_PatenteChanging(string value);
    partial void OnVEHI_PatenteChanged();
    partial void OnTISE_NombreChanging(string value);
    partial void OnTISE_NombreChanged();
    partial void OnCOND_RunChanging(int value);
    partial void OnCOND_RunChanged();
    partial void OnCOND_DvChanging(char value);
    partial void OnCOND_DvChanged();
    partial void OnESTA_NombreChanging(string value);
    partial void OnESTA_NombreChanged();
    partial void OnPOLI_NombreChanging(string value);
    partial void OnPOLI_NombreChanged();
    partial void OnSERC_CodigoChanging(int value);
    partial void OnSERC_CodigoChanged();
    #endregion
		
		public InformacionServicio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_CORD_Latitud", DbType="Float NOT NULL")]
		public double SERC_CORD_Latitud
		{
			get
			{
				return this._SERC_CORD_Latitud;
			}
			set
			{
				if ((this._SERC_CORD_Latitud != value))
				{
					this.OnSERC_CORD_LatitudChanging(value);
					this.SendPropertyChanging();
					this._SERC_CORD_Latitud = value;
					this.SendPropertyChanged("SERC_CORD_Latitud");
					this.OnSERC_CORD_LatitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_CORD_Longitud", DbType="Float NOT NULL")]
		public double SERC_CORD_Longitud
		{
			get
			{
				return this._SERC_CORD_Longitud;
			}
			set
			{
				if ((this._SERC_CORD_Longitud != value))
				{
					this.OnSERC_CORD_LongitudChanging(value);
					this.SendPropertyChanging();
					this._SERC_CORD_Longitud = value;
					this.SendPropertyChanged("SERC_CORD_Longitud");
					this.OnSERC_CORD_LongitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime SERC_Fecha
		{
			get
			{
				return this._SERC_Fecha;
			}
			set
			{
				if ((this._SERC_Fecha != value))
				{
					this.OnSERC_FechaChanging(value);
					this.SendPropertyChanging();
					this._SERC_Fecha = value;
					this.SendPropertyChanged("SERC_Fecha");
					this.OnSERC_FechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_ARCH_Codigo", DbType="Int")]
		public System.Nullable<int> SERC_ARCH_Codigo
		{
			get
			{
				return this._SERC_ARCH_Codigo;
			}
			set
			{
				if ((this._SERC_ARCH_Codigo != value))
				{
					this.OnSERC_ARCH_CodigoChanging(value);
					this.SendPropertyChanging();
					this._SERC_ARCH_Codigo = value;
					this.SendPropertyChanged("SERC_ARCH_Codigo");
					this.OnSERC_ARCH_CodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_Motivo", DbType="VarChar(300)")]
		public string SERC_Motivo
		{
			get
			{
				return this._SERC_Motivo;
			}
			set
			{
				if ((this._SERC_Motivo != value))
				{
					this.OnSERC_MotivoChanging(value);
					this.SendPropertyChanging();
					this._SERC_Motivo = value;
					this.SendPropertyChanged("SERC_Motivo");
					this.OnSERC_MotivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_CodigoActivo", DbType="VarChar(20)")]
		public string SERC_CodigoActivo
		{
			get
			{
				return this._SERC_CodigoActivo;
			}
			set
			{
				if ((this._SERC_CodigoActivo != value))
				{
					this.OnSERC_CodigoActivoChanging(value);
					this.SendPropertyChanging();
					this._SERC_CodigoActivo = value;
					this.SendPropertyChanged("SERC_CodigoActivo");
					this.OnSERC_CodigoActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_NumeroVisible", DbType="VarChar(20)")]
		public string SERC_NumeroVisible
		{
			get
			{
				return this._SERC_NumeroVisible;
			}
			set
			{
				if ((this._SERC_NumeroVisible != value))
				{
					this.OnSERC_NumeroVisibleChanging(value);
					this.SendPropertyChanging();
					this._SERC_NumeroVisible = value;
					this.SendPropertyChanged("SERC_NumeroVisible");
					this.OnSERC_NumeroVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_Volumen", DbType="VarChar(20)")]
		public string SERC_Volumen
		{
			get
			{
				return this._SERC_Volumen;
			}
			set
			{
				if ((this._SERC_Volumen != value))
				{
					this.OnSERC_VolumenChanging(value);
					this.SendPropertyChanging();
					this._SERC_Volumen = value;
					this.SendPropertyChanged("SERC_Volumen");
					this.OnSERC_VolumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_Token", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> SERC_Token
		{
			get
			{
				return this._SERC_Token;
			}
			set
			{
				if ((this._SERC_Token != value))
				{
					this.OnSERC_TokenChanging(value);
					this.SendPropertyChanging();
					this._SERC_Token = value;
					this.SendPropertyChanged("SERC_Token");
					this.OnSERC_TokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTI_Nombre", DbType="VarChar(200)")]
		public string ENTI_Nombre
		{
			get
			{
				return this._ENTI_Nombre;
			}
			set
			{
				if ((this._ENTI_Nombre != value))
				{
					this.OnENTI_NombreChanging(value);
					this.SendPropertyChanging();
					this._ENTI_Nombre = value;
					this.SendPropertyChanged("ENTI_Nombre");
					this.OnENTI_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIE_Nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string CLIE_Nombre
		{
			get
			{
				return this._CLIE_Nombre;
			}
			set
			{
				if ((this._CLIE_Nombre != value))
				{
					this.OnCLIE_NombreChanging(value);
					this.SendPropertyChanging();
					this._CLIE_Nombre = value;
					this.SendPropertyChanged("CLIE_Nombre");
					this.OnCLIE_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUCU_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SUCU_Nombre
		{
			get
			{
				return this._SUCU_Nombre;
			}
			set
			{
				if ((this._SUCU_Nombre != value))
				{
					this.OnSUCU_NombreChanging(value);
					this.SendPropertyChanging();
					this._SUCU_Nombre = value;
					this.SendPropertyChanged("SUCU_Nombre");
					this.OnSUCU_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEHI_Patente", DbType="VarChar(10)")]
		public string VEHI_Patente
		{
			get
			{
				return this._VEHI_Patente;
			}
			set
			{
				if ((this._VEHI_Patente != value))
				{
					this.OnVEHI_PatenteChanging(value);
					this.SendPropertyChanging();
					this._VEHI_Patente = value;
					this.SendPropertyChanged("VEHI_Patente");
					this.OnVEHI_PatenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TISE_Nombre", DbType="VarChar(100)")]
		public string TISE_Nombre
		{
			get
			{
				return this._TISE_Nombre;
			}
			set
			{
				if ((this._TISE_Nombre != value))
				{
					this.OnTISE_NombreChanging(value);
					this.SendPropertyChanging();
					this._TISE_Nombre = value;
					this.SendPropertyChanged("TISE_Nombre");
					this.OnTISE_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COND_Run", DbType="Int NOT NULL")]
		public int COND_Run
		{
			get
			{
				return this._COND_Run;
			}
			set
			{
				if ((this._COND_Run != value))
				{
					this.OnCOND_RunChanging(value);
					this.SendPropertyChanging();
					this._COND_Run = value;
					this.SendPropertyChanged("COND_Run");
					this.OnCOND_RunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COND_Dv", DbType="Char(1) NOT NULL")]
		public char COND_Dv
		{
			get
			{
				return this._COND_Dv;
			}
			set
			{
				if ((this._COND_Dv != value))
				{
					this.OnCOND_DvChanging(value);
					this.SendPropertyChanging();
					this._COND_Dv = value;
					this.SendPropertyChanged("COND_Dv");
					this.OnCOND_DvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTA_Nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ESTA_Nombre
		{
			get
			{
				return this._ESTA_Nombre;
			}
			set
			{
				if ((this._ESTA_Nombre != value))
				{
					this.OnESTA_NombreChanging(value);
					this.SendPropertyChanging();
					this._ESTA_Nombre = value;
					this.SendPropertyChanged("ESTA_Nombre");
					this.OnESTA_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLI_Nombre", CanBeNull=false)]
		public string POLI_Nombre
		{
			get
			{
				return this._POLI_Nombre;
			}
			set
			{
				if ((this._POLI_Nombre != value))
				{
					this.OnPOLI_NombreChanging(value);
					this.SendPropertyChanging();
					this._POLI_Nombre = value;
					this.SendPropertyChanged("POLI_Nombre");
					this.OnPOLI_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERC_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SERC_Codigo
		{
			get
			{
				return this._SERC_Codigo;
			}
			set
			{
				if ((this._SERC_Codigo != value))
				{
					this.OnSERC_CodigoChanging(value);
					this.SendPropertyChanging();
					this._SERC_Codigo = value;
					this.SendPropertyChanged("SERC_Codigo");
					this.OnSERC_CodigoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
