<?xml version="1.0" encoding="utf-8"?><Database Name="RS_MDS_v2" Class="ProgrammingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\MSSQLSERVER_2012;Initial Catalog=RS_MDS_v2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RS_MDS_v2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_MDS_TipoServicio" Member="ProgramacionServicios">
    <Type Name="ProgramacionServicio">
      <Column Name="TISE_Codigo" Member="codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TISE_Nombre" Member="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TISE_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DiasProgramados" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MDS_Programacion" Member="Programacions">
    <Type Name="Programacion">
      <Column Name="PROG_SERVUNEG_Codigo" Member="servicio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PROG_POLI_Codigo" Member="poligono" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PROG_Fecha" Member="fecha" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="PoligonoServicios">
    <Type Name="PoligonoServicio">
      <Column Name="POLI_Nombre" Member="nombre" Type="System.String" CanBeNull="false" />
      <Column Name="POLI_Token" Member="token" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="POLI_Codigo" Member="codigo" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MDS_Programacion" Member="DiaProgramados">
    <Type Name="DiaProgramado">
      <Column Name="" Member="dias" Type="List&lt;System.Int32&gt;" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="POLI_Token" Member="poligono" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Programas">
    <Type Name="Programa">
      <Column Name="POLI_Token" Member="poligono" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TISE_Token" Member="tipo" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>