#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Areas.Resiter.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RS_MDS_v2")]
	public partial class ProgrammingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProgramacionServicio(ProgramacionServicio instance);
    partial void UpdateProgramacionServicio(ProgramacionServicio instance);
    partial void DeleteProgramacionServicio(ProgramacionServicio instance);
    partial void InsertProgramacion(Programacion instance);
    partial void UpdateProgramacion(Programacion instance);
    partial void DeleteProgramacion(Programacion instance);
    partial void InsertPoligonoServicio(PoligonoServicio instance);
    partial void UpdatePoligonoServicio(PoligonoServicio instance);
    partial void DeletePoligonoServicio(PoligonoServicio instance);
    partial void InsertDiaProgramado(DiaProgramado instance);
    partial void UpdateDiaProgramado(DiaProgramado instance);
    partial void DeleteDiaProgramado(DiaProgramado instance);
    partial void InsertPrograma(Programa instance);
    partial void UpdatePrograma(Programa instance);
    partial void DeletePrograma(Programa instance);
    #endregion
		
		public ProgrammingDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RS_MDS_v2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProgrammingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProgrammingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProgrammingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProgrammingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ProgramacionServicio> ProgramacionServicios
		{
			get
			{
				return this.GetTable<ProgramacionServicio>();
			}
		}
		
		public System.Data.Linq.Table<Programacion> Programacions
		{
			get
			{
				return this.GetTable<Programacion>();
			}
		}
		
		public System.Data.Linq.Table<PoligonoServicio> PoligonoServicios
		{
			get
			{
				return this.GetTable<PoligonoServicio>();
			}
		}
		
		public System.Data.Linq.Table<DiaProgramado> DiaProgramados
		{
			get
			{
				return this.GetTable<DiaProgramado>();
			}
		}
		
		public System.Data.Linq.Table<Programa> Programas
		{
			get
			{
				return this.GetTable<Programa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_MDS_TipoServicio")]
	public partial class ProgramacionServicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nombre;
		
		private System.Nullable<System.Guid> _token;
		
		private System.Guid _imagen;
		
		private int _DiasProgramados;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OntokenChanging(System.Nullable<System.Guid> value);
    partial void OntokenChanged();
    partial void OnimagenChanging(System.Guid value);
    partial void OnimagenChanged();
    partial void OnDiasProgramadosChanging(int value);
    partial void OnDiasProgramadosChanged();
    #endregion
		
		public ProgramacionServicio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TISE_Codigo", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TISE_Nombre", Storage="_nombre", DbType="VarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TISE_Token", Storage="_token", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ARCH_Token", Storage="_imagen", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this.OnimagenChanging(value);
					this.SendPropertyChanging();
					this._imagen = value;
					this.SendPropertyChanged("imagen");
					this.OnimagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiasProgramados")]
		public int DiasProgramados
		{
			get
			{
				return this._DiasProgramados;
			}
			set
			{
				if ((this._DiasProgramados != value))
				{
					this.OnDiasProgramadosChanging(value);
					this.SendPropertyChanging();
					this._DiasProgramados = value;
					this.SendPropertyChanged("DiasProgramados");
					this.OnDiasProgramadosChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_MDS_Programacion")]
	public partial class Programacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _servicio;
		
		private int _poligono;
		
		private System.DateTime _fecha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnservicioChanging(int value);
    partial void OnservicioChanged();
    partial void OnpoligonoChanging(int value);
    partial void OnpoligonoChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    #endregion
		
		public Programacion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PROG_SERVUNEG_Codigo", Storage="_servicio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int servicio
		{
			get
			{
				return this._servicio;
			}
			set
			{
				if ((this._servicio != value))
				{
					this.OnservicioChanging(value);
					this.SendPropertyChanging();
					this._servicio = value;
					this.SendPropertyChanged("servicio");
					this.OnservicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PROG_POLI_Codigo", Storage="_poligono", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int poligono
		{
			get
			{
				return this._poligono;
			}
			set
			{
				if ((this._poligono != value))
				{
					this.OnpoligonoChanging(value);
					this.SendPropertyChanging();
					this._poligono = value;
					this.SendPropertyChanged("poligono");
					this.OnpoligonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PROG_Fecha", Storage="_fecha", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class PoligonoServicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nombre;
		
		private System.Guid _token;
		
		private int _codigo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OntokenChanging(System.Guid value);
    partial void OntokenChanged();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    #endregion
		
		public PoligonoServicio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="POLI_Nombre", Storage="_nombre", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="POLI_Token", Storage="_token", IsPrimaryKey=true)]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="POLI_Codigo", Storage="_codigo")]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_MDS_Programacion")]
	public partial class DiaProgramado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private List<System.Int32> _dias;
		
		private System.Guid _poligono;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndiasChanging(List<System.Int32> value);
    partial void OndiasChanged();
    partial void OnpoligonoChanging(System.Guid value);
    partial void OnpoligonoChanged();
    #endregion
		
		public DiaProgramado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_dias", CanBeNull=false, IsPrimaryKey=true)]
		public List<System.Int32> dias
		{
			get
			{
				return this._dias;
			}
			set
			{
				if ((this._dias != value))
				{
					this.OndiasChanging(value);
					this.SendPropertyChanging();
					this._dias = value;
					this.SendPropertyChanged("dias");
					this.OndiasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="POLI_Token", Storage="_poligono", IsPrimaryKey=true)]
		public System.Guid poligono
		{
			get
			{
				return this._poligono;
			}
			set
			{
				if ((this._poligono != value))
				{
					this.OnpoligonoChanging(value);
					this.SendPropertyChanging();
					this._poligono = value;
					this.SendPropertyChanged("poligono");
					this.OnpoligonoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Programa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _poligono;
		
		private System.Guid _tipo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpoligonoChanging(System.Guid value);
    partial void OnpoligonoChanged();
    partial void OntipoChanging(System.Guid value);
    partial void OntipoChanged();
    #endregion
		
		public Programa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="POLI_Token", Storage="_poligono", IsPrimaryKey=true)]
		public System.Guid poligono
		{
			get
			{
				return this._poligono;
			}
			set
			{
				if ((this._poligono != value))
				{
					this.OnpoligonoChanging(value);
					this.SendPropertyChanging();
					this._poligono = value;
					this.SendPropertyChanged("poligono");
					this.OnpoligonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TISE_Token", Storage="_tipo", IsPrimaryKey=true)]
		public System.Guid tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
