#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Areas.Resiter.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RS_MDS_v2")]
	public partial class ReportsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ReportsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RS_MDS_v2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReportsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ServicioRealizado> ServicioRealizados
		{
			get
			{
				return this.GetTable<ServicioRealizado>();
			}
		}
		
		public System.Data.Linq.Table<R_Servicios> R_Servicios
		{
			get
			{
				return this.GetTable<R_Servicios>();
			}
		}
		
		public System.Data.Linq.Table<R_Totales> R_Totales
		{
			get
			{
				return this.GetTable<R_Totales>();
			}
		}
		
		public System.Data.Linq.Table<MovimientosDiarios> MovimientosDiarios
		{
			get
			{
				return this.GetTable<MovimientosDiarios>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_GPS_ServicioConductor")]
	public partial class ServicioRealizado
	{
		
		private double _latitud;
		
		private double _longitud;
		
		private System.DateTime _fecha;
		
		private string _motivo;
		
		private string _codigoActivo;
		
		private string _numeroVisible;
		
		private string _volumen;
		
		private System.Nullable<System.Guid> _token;
		
		private string _conductor;
		
		private string _patente;
		
		private string _poligono;
		
		private System.Nullable<System.Guid> _imagen;
		
		public ServicioRealizado()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SERC_CORD_Latitud", Storage="_latitud", DbType="Float NOT NULL")]
		public double latitud
		{
			get
			{
				return this._latitud;
			}
			set
			{
				if ((this._latitud != value))
				{
					this._latitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SERC_CORD_Longitud", Storage="_longitud", DbType="Float NOT NULL")]
		public double longitud
		{
			get
			{
				return this._longitud;
			}
			set
			{
				if ((this._longitud != value))
				{
					this._longitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SERC_Fecha", Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SERC_Motivo", Storage="_motivo", DbType="VarChar(300)")]
		public string motivo
		{
			get
			{
				return this._motivo;
			}
			set
			{
				if ((this._motivo != value))
				{
					this._motivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SERC_CodigoActivo", Storage="_codigoActivo", DbType="VarChar(20)")]
		public string codigoActivo
		{
			get
			{
				return this._codigoActivo;
			}
			set
			{
				if ((this._codigoActivo != value))
				{
					this._codigoActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SERC_NumeroVisible", Storage="_numeroVisible", DbType="VarChar(20)")]
		public string numeroVisible
		{
			get
			{
				return this._numeroVisible;
			}
			set
			{
				if ((this._numeroVisible != value))
				{
					this._numeroVisible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SERC_Volumen", Storage="_volumen", DbType="VarChar(20)")]
		public string volumen
		{
			get
			{
				return this._volumen;
			}
			set
			{
				if ((this._volumen != value))
				{
					this._volumen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SERC_Token", Storage="_token", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ENTI_Nombre", Storage="_conductor", DbType="VarChar(200)")]
		public string conductor
		{
			get
			{
				return this._conductor;
			}
			set
			{
				if ((this._conductor != value))
				{
					this._conductor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="VEHI_Patente", Storage="_patente", DbType="VarChar(10)")]
		public string patente
		{
			get
			{
				return this._patente;
			}
			set
			{
				if ((this._patente != value))
				{
					this._patente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="POLI_Nombre", Storage="_poligono", CanBeNull=false)]
		public string poligono
		{
			get
			{
				return this._poligono;
			}
			set
			{
				if ((this._poligono != value))
				{
					this._poligono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ARCH_Token", Storage="_imagen")]
		public System.Nullable<System.Guid> imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this._imagen = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class R_Servicios
	{
		
		private string _poligono;
		
		private string _tiposervicio;
		
		private string _fecha;
		
		private string _programados;
		
		private string _programadosrealizados;
		
		private string _programadosfallidos;
		
		private string _pendientes;
		
		private string _adicionalesrealizados;
		
		private string _adicionalesfallidos;
		
		private string _adicionales;
		
		public R_Servicios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="POLI_Nombre", Storage="_poligono", CanBeNull=false)]
		public string poligono
		{
			get
			{
				return this._poligono;
			}
			set
			{
				if ((this._poligono != value))
				{
					this._poligono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TISE_nombre", Storage="_tiposervicio", CanBeNull=false)]
		public string tiposervicio
		{
			get
			{
				return this._tiposervicio;
			}
			set
			{
				if ((this._tiposervicio != value))
				{
					this._tiposervicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Fecha", Storage="_fecha", CanBeNull=false)]
		public string fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Programados", Storage="_programados", CanBeNull=false)]
		public string programados
		{
			get
			{
				return this._programados;
			}
			set
			{
				if ((this._programados != value))
				{
					this._programados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ProgramadosRealizados", Storage="_programadosrealizados", CanBeNull=false)]
		public string programadosrealizados
		{
			get
			{
				return this._programadosrealizados;
			}
			set
			{
				if ((this._programadosrealizados != value))
				{
					this._programadosrealizados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ProgramadosFallidos", Storage="_programadosfallidos", CanBeNull=false)]
		public string programadosfallidos
		{
			get
			{
				return this._programadosfallidos;
			}
			set
			{
				if ((this._programadosfallidos != value))
				{
					this._programadosfallidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Pendientes", Storage="_pendientes", CanBeNull=false)]
		public string pendientes
		{
			get
			{
				return this._pendientes;
			}
			set
			{
				if ((this._pendientes != value))
				{
					this._pendientes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AdicionalesRealizados", Storage="_adicionalesrealizados", CanBeNull=false)]
		public string adicionalesrealizados
		{
			get
			{
				return this._adicionalesrealizados;
			}
			set
			{
				if ((this._adicionalesrealizados != value))
				{
					this._adicionalesrealizados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AdicionalesFallidos", Storage="_adicionalesfallidos", CanBeNull=false)]
		public string adicionalesfallidos
		{
			get
			{
				return this._adicionalesfallidos;
			}
			set
			{
				if ((this._adicionalesfallidos != value))
				{
					this._adicionalesfallidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Adicionales", Storage="_adicionales", CanBeNull=false)]
		public string adicionales
		{
			get
			{
				return this._adicionales;
			}
			set
			{
				if ((this._adicionales != value))
				{
					this._adicionales = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class R_Totales
	{
		
		private string _programados;
		
		private string _programadosrealizados;
		
		private string _programadosfallidos;
		
		private string _pendientes;
		
		private string _adicionalesrealizados;
		
		private string _adicionalesfallidos;
		
		private string _adicionales;
		
		public R_Totales()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Programados", Storage="_programados", CanBeNull=false)]
		public string programados
		{
			get
			{
				return this._programados;
			}
			set
			{
				if ((this._programados != value))
				{
					this._programados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ProgramadosRealizados", Storage="_programadosrealizados", CanBeNull=false)]
		public string programadosrealizados
		{
			get
			{
				return this._programadosrealizados;
			}
			set
			{
				if ((this._programadosrealizados != value))
				{
					this._programadosrealizados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ProgramadosFallidos", Storage="_programadosfallidos", CanBeNull=false)]
		public string programadosfallidos
		{
			get
			{
				return this._programadosfallidos;
			}
			set
			{
				if ((this._programadosfallidos != value))
				{
					this._programadosfallidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Pendientes", Storage="_pendientes", CanBeNull=false)]
		public string pendientes
		{
			get
			{
				return this._pendientes;
			}
			set
			{
				if ((this._pendientes != value))
				{
					this._pendientes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AdicionalesRealizados", Storage="_adicionalesrealizados", CanBeNull=false)]
		public string adicionalesrealizados
		{
			get
			{
				return this._adicionalesrealizados;
			}
			set
			{
				if ((this._adicionalesrealizados != value))
				{
					this._adicionalesrealizados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AdicionalesFallidos", Storage="_adicionalesfallidos", CanBeNull=false)]
		public string adicionalesfallidos
		{
			get
			{
				return this._adicionalesfallidos;
			}
			set
			{
				if ((this._adicionalesfallidos != value))
				{
					this._adicionalesfallidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Adicionales", Storage="_adicionales", CanBeNull=false)]
		public string adicionales
		{
			get
			{
				return this._adicionales;
			}
			set
			{
				if ((this._adicionales != value))
				{
					this._adicionales = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class MovimientosDiarios
	{
		
		private System.DateTime _fechaaccion;
		
		private System.DateTime _fechareal;
		
		private string _nombre;
		
		private decimal _latitud;
		
		private decimal _longitud;
		
		private string _accionrealizada;
		
		private string _codigoqr;
		
		private string _patente;
		
		private string _fabricacion;
		
		private string _poligono;
		
		private string _tipocontenedor;
		
		private string _porcentajellenado;
		
		private string _adicional;
		
		public MovimientosDiarios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FECHA_ACCION", Storage="_fechaaccion")]
		public System.DateTime fechaaccion
		{
			get
			{
				return this._fechaaccion;
			}
			set
			{
				if ((this._fechaaccion != value))
				{
					this._fechaaccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FECHA_REAL", Storage="_fechareal")]
		public System.DateTime fechareal
		{
			get
			{
				return this._fechareal;
			}
			set
			{
				if ((this._fechareal != value))
				{
					this._fechareal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="NOMBRE", Storage="_nombre", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LATITUD", Storage="_latitud")]
		public decimal latitud
		{
			get
			{
				return this._latitud;
			}
			set
			{
				if ((this._latitud != value))
				{
					this._latitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LONGITUD", Storage="_longitud")]
		public decimal longitud
		{
			get
			{
				return this._longitud;
			}
			set
			{
				if ((this._longitud != value))
				{
					this._longitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ACCION_REALIZADA", Storage="_accionrealizada", CanBeNull=false)]
		public string accionrealizada
		{
			get
			{
				return this._accionrealizada;
			}
			set
			{
				if ((this._accionrealizada != value))
				{
					this._accionrealizada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CODIGO_QR", Storage="_codigoqr", CanBeNull=false)]
		public string codigoqr
		{
			get
			{
				return this._codigoqr;
			}
			set
			{
				if ((this._codigoqr != value))
				{
					this._codigoqr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PATENTE", Storage="_patente", CanBeNull=false)]
		public string patente
		{
			get
			{
				return this._patente;
			}
			set
			{
				if ((this._patente != value))
				{
					this._patente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FABRICACION", Storage="_fabricacion", CanBeNull=false)]
		public string fabricacion
		{
			get
			{
				return this._fabricacion;
			}
			set
			{
				if ((this._fabricacion != value))
				{
					this._fabricacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="POLIGONO", Storage="_poligono", CanBeNull=false)]
		public string poligono
		{
			get
			{
				return this._poligono;
			}
			set
			{
				if ((this._poligono != value))
				{
					this._poligono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TIPO_CONTENEDOR", Storage="_tipocontenedor", CanBeNull=false)]
		public string tipocontenedor
		{
			get
			{
				return this._tipocontenedor;
			}
			set
			{
				if ((this._tipocontenedor != value))
				{
					this._tipocontenedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PORCENTAJE_LLENADO", Storage="_porcentajellenado", CanBeNull=false)]
		public string porcentajellenado
		{
			get
			{
				return this._porcentajellenado;
			}
			set
			{
				if ((this._porcentajellenado != value))
				{
					this._porcentajellenado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ADICIONAL", Storage="_adicional", CanBeNull=false)]
		public string adicional
		{
			get
			{
				return this._adicional;
			}
			set
			{
				if ((this._adicional != value))
				{
					this._adicional = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
