<?xml version="1.0" encoding="utf-8"?><Database Name="RS_MDS_v2" Class="ReportsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\MSSQLSERVER_2012;Initial Catalog=RS_MDS_v2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RS_MDS_v2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_GPS_ServicioConductor" Member="ServicioRealizados">
    <Type Name="ServicioRealizado">
      <Column Name="SERC_CORD_Latitud" Member="latitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SERC_CORD_Longitud" Member="longitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SERC_Fecha" Member="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SERC_Motivo" Member="motivo" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="SERC_CodigoActivo" Member="codigoActivo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SERC_NumeroVisible" Member="numeroVisible" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SERC_Volumen" Member="volumen" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SERC_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ENTI_Nombre" Member="conductor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="VEHI_Patente" Member="patente" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLI_Nombre" Member="poligono" Type="System.String" CanBeNull="false" />
      <Column Name="ARCH_Token" Member="imagen" Type="System.Guid" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="R_Servicios">
    <Type Name="R_Servicios">
      <Column Name="POLI_Nombre" Member="poligono" Type="System.String" CanBeNull="false" />
      <Column Name="TISE_nombre" Member="tiposervicio" Type="System.String" CanBeNull="false" />
      <Column Name="RUTA_Fecha" Member="fecha" Type="System.String" CanBeNull="false" />
      <Column Name="Programados" Member="programados" Type="System.String" CanBeNull="false" />
      <Column Name="ProgramadosRealizados" Member="programadosrealizados" Type="System.String" CanBeNull="false" />
      <Column Name="ProgramadosFallidos" Member="programadosfallidos" Type="System.String" CanBeNull="false" />
      <Column Name="Pendientes" Member="pendientes" Type="System.String" CanBeNull="false" />
      <Column Name="AdicionalesRealizados" Member="adicionalesrealizados" Type="System.String" CanBeNull="false" />
      <Column Name="AdicionalesFallidos" Member="adicionalesfallidos" Type="System.String" CanBeNull="false" />
      <Column Name="Adicionales" Member="adicionales" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="R_Totales">
    <Type Name="R_Totales">
      <Column Name="Programados" Member="programados" Type="System.String" CanBeNull="false" />
      <Column Name="ProgramadosRealizados" Member="programadosrealizados" Type="System.String" CanBeNull="false" />
      <Column Name="ProgramadosFallidos" Member="programadosfallidos" Type="System.String" CanBeNull="false" />
      <Column Name="Pendientes" Member="pendientes" Type="System.String" CanBeNull="false" />
      <Column Name="AdicionalesRealizados" Member="adicionalesrealizados" Type="System.String" CanBeNull="false" />
      <Column Name="AdicionalesFallidos" Member="adicionalesfallidos" Type="System.String" CanBeNull="false" />
      <Column Name="Adicionales" Member="adicionales" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="MovimientosDiarios">
    <Type Name="MovimientosDiarios">
      <Column Name="FECHA_ACCION" Member="fechaaccion" Type="System.DateTime" CanBeNull="false" />
      <Column Name="FECHA_REAL" Member="fechareal" Type="System.DateTime" CanBeNull="false" />
      <Column Name="NOMBRE" Member="nombre" Type="System.String" CanBeNull="false" />
      <Column Name="LATITUD" Member="latitud" Type="System.Decimal" CanBeNull="false" />
      <Column Name="LONGITUD" Member="longitud" Type="System.Decimal" CanBeNull="false" />
      <Column Name="ACCION_REALIZADA" Member="accionrealizada" Type="System.String" CanBeNull="false" />
      <Column Name="CODIGO_QR" Member="codigoqr" Type="System.String" CanBeNull="false" />
      <Column Name="PATENTE" Member="patente" Type="System.String" CanBeNull="false" />
      <Column Name="FABRICACION" Member="fabricacion" Type="System.String" CanBeNull="false" />
      <Column Name="POLIGONO" Member="poligono" Type="System.String" CanBeNull="false" />
      <Column Name="TIPO_CONTENEDOR" Member="tipocontenedor" Type="System.String" CanBeNull="false" />
      <Column Name="PORCENTAJE_LLENADO" Member="porcentajellenado" Type="System.String" CanBeNull="false" />
      <Column Name="ADICIONAL" Member="adicional" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>